SET(BEAST_LIB_TARGET_NAME BeastEngine)

set(BEAST_INCLUDE_DIR "${${PROJECT_MAIN_NAME}_SOURCE_DIR}/include")
set(BEAST_SRC_DIR "${${PROJECT_MAIN_NAME}_SOURCE_DIR}/src")

set(BEAST_HEADERS_PREFIX "${BEAST_INCLUDE_DIR}/${BEAST_LIB_TARGET_NAME}/")
set(BEAST_SRC_PREFIX "${BEAST_SRC_DIR}/${BEAST_LIB_TARGET_NAME}/")
