SET(BE_MATH_LIB_TARGET_NAME Math)

set(BE_MATH_INCLUDE_DIR "${${PROJECT_MAIN_NAME}_SOURCE_DIR}/include")
set(BE_MATH_SRC_DIR "${${PROJECT_MAIN_NAME}_SOURCE_DIR}/src")

set(BE_MATH_HEADERS_PREFIX "${BE_MATH_INCLUDE_DIR}/${BE_MATH_LIB_TARGET_NAME}/")
set(BE_MATH_SRC_PREFIX "${BE_MATH_SRC_DIR}/${BE_MATH_LIB_TARGET_NAME}/")

set(
	BE_MATH_HEADERS_LIST
	"Types.h"
)
set(
	BE_MATH_SRC_LIST
)

list(TRANSFORM BE_MATH_HEADERS_LIST PREPEND ${BE_MATH_HEADERS_PREFIX})
list(TRANSFORM BE_MATH_SRC_LIST PREPEND ${BE_MATH_SRC_PREFIX})

add_library(${BE_MATH_LIB_TARGET_NAME} INTERFACE "${BE_MATH_SRC_LIST}" "${BE_MATH_HEADERS_LIST}")
target_include_directories(${BE_MATH_LIB_TARGET_NAME} INTERFACE "${BE_MATH_INCLUDE_DIR}")
target_compile_features(${BE_MATH_LIB_TARGET_NAME} INTERFACE cxx_std_17)

target_link_libraries(
	${BE_MATH_LIB_TARGET_NAME}
    INTERFACE
		CONAN_PKG::glm
)

# Group files into proper folders - for IDE
be_group_files("${BE_MATH_HEADERS_LIST}" "${BE_MATH_INCLUDE_DIR}")
be_group_files("${BE_MATH_SRC_LIST}" "${BE_MATH_SRC_DIR}")

add_library(BE::math ALIAS ${BE_MATH_LIB_TARGET_NAME})
