function(be_set_compiler_options IN_TARGET_NAME)
    if(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
        target_compile_options(${IN_TARGET_NAME} PRIVATE /EHsc /WX /W4 /c /experimental:external /external:anglebrackets /external:W0 /MP)
    endif()
    target_compile_features(${IN_TARGET_NAME} PUBLIC cxx_std_20)
endfunction(be_set_compiler_options)

function(be_set_compiler_interface_options IN_TARGET_NAME)
    if(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
        target_compile_options(${IN_TARGET_NAME} INTERFACE /EHsc /WX /W4 /c /experimental:external /external:anglebrackets /external:W0 /MP)
    endif()
    target_compile_features(${IN_TARGET_NAME} INTERFACE cxx_std_20)
endfunction(be_set_compiler_interface_options)
